Repository ZB-Online/Peach-in, pull requests merged in 2021-12, with the labels that each got.

#5 #4 feature/state: add client side state
  package.json
  public/js/store/scheduler.js
Labels: enhancement, ReviewMe

#6 #1 feature/server: set up mock server
  package-lock.json
  package.json
  server.js
Labels: enhancement, ReviewMe

#11 #10 Feat: modify server
  server.js
Labels: bug

#12 #10 Style: modify mock data
  server.js
Labels: bug, ReviewMe

#14 #13 feature/add server communication
  public/js/store/scheduler.js
  public/js/utils/fetch.js
Labels: enhancement, ReviewMe

#17 Feature/popup
  .eslintrc.json
  .gitignore
  public/js/modal/app.js
  public/js/modal/modal.html
  public/js/modal/style.css
Labels: enhancement, ReviewMe

#24 Feature/timeblock
  public/js/timeblock/timeblock.html
  public/js/timeblock/timeblock.js
  server.js
Labels: enhancement, ReviewMe

#28 #27 feature/timeblock remove btn
  public/js/timeblock/timeblock.html
  public/js/timeblock/timeblock.js
Labels: enhancement, ReviewMe

#30 #3 feature/set up calendar
  public/js/calendar/calendar.js
  public/js/calendar/index.html
  public/js/calendar/style.css
Labels: enhancement, ReviewMe

#31 #29 feature/add calendar mouse drag
  .vscode/settings.json
  public/js/calendar_mouseDrag/app.js
Labels: enhancement, ReviewMe

#32 #25 feat: add update and delete modal
  public/js/modal/app.js
  public/js/modal/helper.js
  public/js/modal/modal.html
  public/js/modal/modal.js
  public/js/modal/style.css
  public/js/store/scheduler.js
  public/js/timeblock/timeblock.js
  server.js
Labels: enhancement, ReviewMe

#41 Release 3
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  public/css/calendar.css
  public/css/kanban.css
  public/css/modal.css
  public/css/style.css
  public/css/tooltip.css
  public/img/icon1.png
  public/img/icon2.png
  public/img/icon3.png
  public/img/icon4.png
  public/index.html
  public/js/app.js
  public/js/calendar/calendar.js
  public/js/calendar/dragevent.js
  public/js/calendar/state.js
  public/js/calendar/timeblock.js
  public/js/kanban/kanban.js
  public/js/scheduler/app.js
  public/js/scheduler/render.js
  public/js/store/scheduler.js
  public/js/utils/fetch.js
  public/js/utils/helper.js
  server.js
Labels: ReviewMe
